# Generated by Django 2.2.10 on 2020-07-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200523_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_ico',
            field=models.ImageField(default='text', upload_to=''),
            preserve_default=False,
        ),
    ]
