# Generated by Django 2.2.10 on 2020-07-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Loyality',
        ),
    ]
