# Generated by Django 2.2.10 on 2020-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20200716_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('reward', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Loyality',
        ),
    ]
