# Generated by Django 2.2.10 on 2020-07-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_skill_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='mainsite.Difficulty'),
        ),
    ]
