# Generated by Django 2.2.10 on 2020-07-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_skill_diffictatlty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='diffictatlty',
            new_name='difficultly',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_ico',
            field=models.ImageField(upload_to='img'),
        ),
    ]
