# Generated by Django 2.2.10 on 2020-07-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20200723_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='difficultly',
            new_name='difficulty',
        ),
    ]
