# Generated by Django 2.2.13 on 2020-08-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20200723_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sphere_of_life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
