# Generated by Django 2.2.13 on 2020-11-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_user_affirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_affirmation',
            options={'ordering': ['-user'], 'verbose_name': 'Аффирмация', 'verbose_name_plural': 'Пользовательские аффирмации'},
        ),
    ]
