# Generated by Django 3.1.3 on 2020-11-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0016_userachivement_achivement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphere_of_life',
            name='career',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Учеба\\Карьера'),
        ),
        migrations.AlterField(
            model_name='sphere_of_life',
            name='health',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Здоровье'),
        ),
        migrations.AlterField(
            model_name='sphere_of_life',
            name='inside_world',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Внутренний мир'),
        ),
        migrations.AlterField(
            model_name='sphere_of_life',
            name='relationships',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Отношения'),
        ),
        migrations.AlterField(
            model_name='sphere_of_life',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
