# Generated by Django 2.2.13 on 2020-12-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20201127_2237'),
        ('mainsite', '0016_auto_20201130_1514'),
    ]

    operations = [
    ]
