# Generated by Django 2.2.13 on 2020-12-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_merge_20201206_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_affirmation',
        ),
    ]
