# Generated by Django 2.2.13 on 2020-12-06 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0019_delete_user_affirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_affirmation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('date_change', models.DateTimeField(blank=True, null=True)),
                ('background_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аффирмация',
                'verbose_name_plural': 'Пользовательские аффирмации',
                'ordering': ['-user'],
            },
        ),
    ]
