# Generated by Django 3.1.3 on 2021-02-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_user_affirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_affirmation',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user_affirmation',
            name='font_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
