# Generated by Django 3.1.3 on 2021-02-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_auto_20210204_1049'),
        ('mainsite', '0021_auto_20210208_1210'),
    ]

    operations = [
    ]
