# Generated by Django 3.1.3 on 2021-03-09 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_auto_20210309_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_affirmation',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
