# Generated by Django 3.1.6 on 2021-03-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0028_auto_20210316_1816'),
        ('mainsite', '0024_post_likes'),
    ]

    operations = [
    ]
