# Generated by Django 3.1.3 on 2021-03-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_comment'),
        ('mainsite', '0024_merge_20210309_0139'),
        ('mainsite', '0028_auto_20210316_1816'),
    ]

    operations = [
    ]
