# Generated by Django 3.1.6 on 2021-04-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0030_post_views'),
        ('mainsite', '0029_merge_20210318_2243'),
    ]

    operations = [
    ]
