# Generated by Django 3.1.8 on 2021-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0033_auto_20210418_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction_chapter_lider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default='0')),
                ('user_likes', models.BooleanField(default=False)),
                ('views', models.IntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
