# Generated by Django 3.1.8 on 2021-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0034_auto_20210526_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction_chapter_spheres_life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default='0')),
                ('user_likes', models.BooleanField(default=False)),
                ('views', models.IntegerField(default='0')),
            ],
        ),
    ]
